// Auto-generated by scripts/discover_components.js
// Lazy (code-split) imports — loaded on-demand via Stimulus lazy API
// Do not edit manually

import { application } from "./application"

application.register('admin--dashboard--stat-card-component', () => import('../../components/admin/dashboard/stat_card_component/stat_card_component_controller.js'))

application.register('admin--dashboard-component', () => import('../../components/admin/dashboard_component/dashboard_component_controller.js'))

application.register('admin--poi--show-component', () => import('../../components/admin/poi/show_component/show_component_controller.js'))

application.register('admin--poi--table-component', () => import('../../components/admin/poi/table_component/table_component_controller.js'))

application.register('admin--poi-category--fields-list-component', () => import('../../components/admin/poi_category/fields_list_component/fields_list_component_controller.js'))

application.register('admin--poi-category--show-component', () => import('../../components/admin/poi_category/show_component/show_component_controller.js'))

application.register('admin--poi-category--table-component', () => import('../../components/admin/poi_category/table_component/table_component_controller.js'))

application.register('admin--users--row-component', () => import('../../components/admin/users/row_component/row_component_controller.js'))

application.register('admin--users--table-component', () => import('../../components/admin/users/table_component/table_component_controller.js'))

application.register('admin--users--user--activity-component', () => import('../../components/admin/users/user/activity_component/activity_component_controller.js'))

application.register('admin--users--user--audit-log-component', () => import('../../components/admin/users/user/audit_log_component/audit_log_component_controller.js'))

application.register('admin--users--user--edit-component', () => import('../../components/admin/users/user/edit_component/edit_component_controller.js'))

application.register('admin--users--user--show-component', () => import('../../components/admin/users/user/show_component/show_component_controller.js'))

application.register('admin--users--user--wallet-component', () => import('../../components/admin/users/user/wallet_component/wallet_component_controller.js'))

application.register('poi--detail-component', () => import('../../components/poi/detail_component/detail_component_controller.js'))

application.register('poi--list-item-component', () => import('../../components/poi/list_item_component/list_item_component_controller.js'))

application.register('poi--map-component', () => import('../../components/poi/map_component/map_component_controller.js'))

application.register('settings--field-component', () => import('../../components/settings/field_component/field_component_controller.js'))

application.register('users--form-component', () => import('../../components/users/form_component/form_component_controller.js'))

application.register('users--profile-component', () => import('../../components/users/profile_component/profile_component_controller.js'))
