// Auto-generated by scripts/discover_components.js
// ALL controllers are LAZY (code-split) — loaded on-demand via dynamic import()
// Do not edit manually

import { application } from "./application"

application.register('admin--dashboard--stat-card-component', () => import('../../components/admin/dashboard/stat_card_component/stat_card_component_controller.js'))

application.register('admin--dashboard-component', () => import('../../components/admin/dashboard_component/dashboard_component_controller.js'))

application.register('admin--poi-categories--fields-list-component', () => import('../../components/admin/poi_categories/fields_list_component/fields_list_component_controller.js'))

application.register('admin--poi-categories--poi-category--audit-log-component', () => import('../../components/admin/poi_categories/poi_category/audit_log_component/audit_log_component_controller.js'))

application.register('admin--poi-categories--poi-category--edit-component', () => import('../../components/admin/poi_categories/poi_category/edit_component/edit_component_controller.js'))

application.register('admin--poi-categories--poi-category--pois-list-component', () => import('../../components/admin/poi_categories/poi_category/pois_list_component/pois_list_component_controller.js'))

application.register('admin--poi-categories--poi-category--show-component', () => import('../../components/admin/poi_categories/poi_category/show_component/show_component_controller.js'))

application.register('admin--poi-categories--row-component', () => import('../../components/admin/poi_categories/row_component/row_component_controller.js'))

application.register('admin--poi-categories--table-component', () => import('../../components/admin/poi_categories/table_component/table_component_controller.js'))

application.register('admin--pois--poi--audit-log-component', () => import('../../components/admin/pois/poi/audit_log_component/audit_log_component_controller.js'))

application.register('admin--pois--poi--edit-component', () => import('../../components/admin/pois/poi/edit_component/edit_component_controller.js'))

application.register('admin--pois--poi--show-component', () => import('../../components/admin/pois/poi/show_component/show_component_controller.js'))

application.register('admin--pois--row-component', () => import('../../components/admin/pois/row_component/row_component_controller.js'))

application.register('admin--pois--table-component', () => import('../../components/admin/pois/table_component/table_component_controller.js'))

application.register('admin--users--row-component', () => import('../../components/admin/users/row_component/row_component_controller.js'))

application.register('admin--users--table-component', () => import('../../components/admin/users/table_component/table_component_controller.js'))

application.register('admin--users--user--activity-component', () => import('../../components/admin/users/user/activity_component/activity_component_controller.js'))

application.register('admin--users--user--audit-log-component', () => import('../../components/admin/users/user/audit_log_component/audit_log_component_controller.js'))

application.register('admin--users--user--edit-component', () => import('../../components/admin/users/user/edit_component/edit_component_controller.js'))

application.register('admin--users--user--show-component', () => import('../../components/admin/users/user/show_component/show_component_controller.js'))

application.register('admin--users--user--wallet-component', () => import('../../components/admin/users/user/wallet_component/wallet_component_controller.js'))

application.register('poi--detail-component', () => import('../../components/poi/detail_component/detail_component_controller.js'))

application.register('poi--filters-component', () => import('../../components/poi/filters_component/filters_component_controller.js'))

application.register('poi--list-item-component', () => import('../../components/poi/list_item_component/list_item_component_controller.js'))

application.register('poi--map-component', () => import('../../components/poi/map_component/map_component_controller.js'))

application.register('settings--field-component', () => import('../../components/settings/field_component/field_component_controller.js'))

application.register('ui--avatar-component', () => import('../../components/ui/avatar_component/avatar_component_controller.js'))

application.register('ui--badge-component', () => import('../../components/ui/badge_component/badge_component_controller.js'))

application.register('ui--breadcrumbs-component', () => import('../../components/ui/breadcrumbs_component/breadcrumbs_component_controller.js'))

application.register('ui--btn-component', () => import('../../components/ui/btn_component/btn_component_controller.js'))

application.register('ui--card-component', () => import('../../components/ui/card_component/card_component_controller.js'))

application.register('ui--clipboard-component', () => import('../../components/ui/clipboard_component/clipboard_component_controller.js'))

application.register('ui--confirm-dialog-component', () => import('../../components/ui/confirm_dialog_component/confirm_dialog_component_controller.js'))

application.register('ui--dropdown-component', () => import('../../components/ui/dropdown_component/dropdown_component_controller.js'))

application.register('ui--filters-component', () => import('../../components/ui/filters_component/filters_component_controller.js'))

application.register('ui--hamburger-component', () => import('../../components/ui/hamburger_component/hamburger_component_controller.js'))

application.register('ui--navbar-component', () => import('../../components/ui/navbar_component/navbar_component_controller.js'))

application.register('ui--pagination-component', () => import('../../components/ui/pagination_component/pagination_component_controller.js'))

application.register('ui--sidebar-component', () => import('../../components/ui/sidebar_component/sidebar_component_controller.js'))

application.register('ui--tabs-component', () => import('../../components/ui/tabs_component/tabs_component_controller.js'))

application.register('ui--toast-component', () => import('../../components/ui/toast_component/toast_component_controller.js'))

application.register('ui--tooltip-component', () => import('../../components/ui/tooltip_component/tooltip_component_controller.js'))

application.register('users--form-component', () => import('../../components/users/form_component/form_component_controller.js'))

application.register('users--profile-component', () => import('../../components/users/profile_component/profile_component_controller.js'))
