// Auto-generated by scripts/discover_components.js
// Static imports — always included in main bundle
// Do not edit manually

import { application } from "./application"

import ui__avatar_componentController from '../../components/ui/avatar_component/avatar_component_controller.js'
application.register('ui--avatar-component', ui__avatar_componentController)

import ui__badge_componentController from '../../components/ui/badge_component/badge_component_controller.js'
application.register('ui--badge-component', ui__badge_componentController)

import ui__breadcrumbs_componentController from '../../components/ui/breadcrumbs_component/breadcrumbs_component_controller.js'
application.register('ui--breadcrumbs-component', ui__breadcrumbs_componentController)

import ui__btn_componentController from '../../components/ui/btn_component/btn_component_controller.js'
application.register('ui--btn-component', ui__btn_componentController)

import ui__card_componentController from '../../components/ui/card_component/card_component_controller.js'
application.register('ui--card-component', ui__card_componentController)

import ui__clipboard_componentController from '../../components/ui/clipboard_component/clipboard_component_controller.js'
application.register('ui--clipboard-component', ui__clipboard_componentController)

import ui__confirm_dialog_componentController from '../../components/ui/confirm_dialog_component/confirm_dialog_component_controller.js'
application.register('ui--confirm-dialog-component', ui__confirm_dialog_componentController)

import ui__dropdown_componentController from '../../components/ui/dropdown_component/dropdown_component_controller.js'
application.register('ui--dropdown-component', ui__dropdown_componentController)

import ui__filters_componentController from '../../components/ui/filters_component/filters_component_controller.js'
application.register('ui--filters-component', ui__filters_componentController)

import ui__hamburger_componentController from '../../components/ui/hamburger_component/hamburger_component_controller.js'
application.register('ui--hamburger-component', ui__hamburger_componentController)

import ui__navbar_componentController from '../../components/ui/navbar_component/navbar_component_controller.js'
application.register('ui--navbar-component', ui__navbar_componentController)

import ui__pagination_componentController from '../../components/ui/pagination_component/pagination_component_controller.js'
application.register('ui--pagination-component', ui__pagination_componentController)

import ui__sidebar_componentController from '../../components/ui/sidebar_component/sidebar_component_controller.js'
application.register('ui--sidebar-component', ui__sidebar_componentController)

import ui__toast_componentController from '../../components/ui/toast_component/toast_component_controller.js'
application.register('ui--toast-component', ui__toast_componentController)

import ui__tooltip_componentController from '../../components/ui/tooltip_component/tooltip_component_controller.js'
application.register('ui--tooltip-component', ui__tooltip_componentController)
