default: &default
  
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'user' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
  # Для локальной разработки: без DATABASE_HOST — localhost
  # Для запуска в контейнерах: DATABASE_HOST=postgres
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>

development:
  primary:
    <<: *default
    adapter: postgis
    database: travel_fi_dev
    schema_search_path: public,postgis
  queue:
    <<: *default
    adapter: postgresql
    database: travel_fi_dev_queue
    database_tasks: false
  cache:
    <<: *default
    adapter: postgresql
    database: travel_fi_dev_cache
    database_tasks: false
  cable:
    <<: *default
    adapter: postgresql
    database: travel_fi_dev_cable
    database_tasks: false

test:
  primary:
    <<: *default
    adapter: postgis
    database: travel_fi_test
    schema_search_path: public,postgis
  queue: &test_queue
    <<: *default
    adapter: postgresql
    database: travel_fi_test_queue
    database_tasks: false
  cache:
    <<: *default
    adapter: postgresql
    database: travel_fi_test_cache
    database_tasks: false
  cable:
    <<: *default
    adapter: postgresql
    database: travel_fi_test_cable
    database_tasks: false

production:
  primary:
    <<: *default
    adapter: postgis
    database: travel_fi_prod
    password: <%= ENV["TRAVEL_FI_DATABASE_PASSWORD"] %>
    schema_search_path: public,postgis
  queue:
    <<: *default
    adapter: postgresql
    database: travel_fi_prod_queue
    schema_search_path: public,postgis
  cache:
    <<: *default
    adapter: postgresql
    database: travel_fi_prod_cache
    schema_search_path: public,postgis
  cable:
    <<: *default
    adapter: postgresql
    database: travel_fi_prod_cable
    schema_search_path: public,postgis