#!/usr/bin/env node

/**
 * discover_components.js
 *
 * Сканирует app/components/ на наличие Stimulus-контроллеров (*_controller.js)
 * и CSS-файлов (*.css), генерирует:
 *   1. app/javascript/controllers/_components_lazy.js — все контроллеры ленивые
 *   2. app/javascript/controllers/_components.css     — импорт всех sidecar CSS
 *
 * Все компоненты — ленивые (lazy). Stimulus загружает их по требованию
 * при появлении data-controller="..." в DOM.
 *
 * Запуск: node scripts/discover_components.js
 * Автоматически вызывается перед esbuild сборкой.
 */

const fs = require('fs')
const path = require('path')

const COMPONENTS_DIR = path.join(process.cwd(), 'app/components')
const OUTPUT_LAZY_JS = path.join(process.cwd(), 'app/javascript/controllers/_components_lazy.js')
const OUTPUT_CSS = path.join(process.cwd(), 'app/javascript/controllers/_components.css')

function pathToControllerName(filePath) {
  const withoutSuffix = filePath.replace(/_controller\.js$/, '')
  const segments = withoutSuffix.split('/')
  const uniqueSegments = []
  for (let i = 0; i < segments.length; i++) {
    if (i === segments.length - 1 && i > 0 && segments[i] === segments[i - 1]) continue
    uniqueSegments.push(segments[i])
  }
  return uniqueSegments.map(s => s.replace(/_/g, '-')).join('--')
}

function scanFiles(dir, pattern) {
  const results = []
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      const relativePath = path.relative(COMPONENTS_DIR, fullPath)
      if (entry.isDirectory()) {
        results.push(...scanFiles(fullPath, pattern))
      } else if (entry.isFile() && entry.name.endsWith(pattern)) {
        results.push(relativePath)
      }
    }
  } catch (err) {
    console.error(`❌ discover_components: Error scanning ${dir}: ${err.message}`)
  }
  return results
}

function generateLazyJS(controllerFiles) {
  const lines = [
    '// Auto-generated by scripts/discover_components.js',
    '// ALL controllers are LAZY (code-split) — loaded on-demand via dynamic import()',
    '// Do not edit manually',
    '',
    'import { application } from "./application"',
    '',
  ]

  for (const file of controllerFiles) {
    const controllerName = pathToControllerName(file)
    const rawPath = path.relative(
      path.join(process.cwd(), 'app/javascript/controllers'),
      path.join(COMPONENTS_DIR, file)
    )
    const importPath = rawPath.startsWith('.') ? rawPath : './' + rawPath
    lines.push(
      `application.register('${controllerName}', () => import('${importPath}'))`
    )
    lines.push('')
  }

  fs.writeFileSync(OUTPUT_LAZY_JS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_LAZY_JS} (${controllerFiles.length} lazy controllers)`)
}

function generateCSS(cssFiles) {
  const lines = [
    '/* Auto-generated by scripts/discover_components.js */',
    '/* Do not edit manually — CSS content is inlined, not @import */',
    '',
  ]

  for (const file of cssFiles) {
    const fullPath = path.join(COMPONENTS_DIR, file)
    try {
      const content = fs.readFileSync(fullPath, 'utf-8').trim()
      if (!content || (content.startsWith('/*') && content.endsWith('*/'))) continue
      lines.push(`/* === ${file} === */`)
      lines.push(content)
      lines.push('')
    } catch (err) {
      console.warn(`⚠️  discover_components: Could not read ${file}: ${err.message}`)
    }
  }

  fs.writeFileSync(OUTPUT_CSS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_CSS} (${cssFiles.length} CSS files)`)
}

function generate() {
  console.log('🔍 discover_components: Scanning app/components/...')

  const controllerFiles = scanFiles(COMPONENTS_DIR, '_controller.js')
  const cssFiles = scanFiles(COMPONENTS_DIR, '.css')

  // Удаляем старый _components_index.js (больше не нужен)
  const oldIndex = path.join(process.cwd(), 'app/javascript/controllers/_components_index.js')
  if (fs.existsSync(oldIndex)) {
    fs.unlinkSync(oldIndex)
    console.log('   Removed _components_index.js (all controllers are now lazy)')
  }

  generateLazyJS(controllerFiles)
  generateCSS(cssFiles)

  controllerFiles.forEach(f => console.log(`   LAZY → ${pathToControllerName(f)}`))
  cssFiles.forEach(f => console.log(`   CSS → ${f}`))
}

generate()
