#!/usr/bin/env node

/**
 * discover_components.js
 *
 * Сканирует app/components/ на наличие Stimulus-контроллеров (*_controller.js)
 * и CSS-файлов (*.css), генерирует:
 *   1. app/javascript/controllers/_components_index.js — все контроллеры EAGER
 *   2. app/javascript/controllers/_components.css     — импорт всех sidecar CSS
 *   3. .stimulus-lsp/config.json — synchronized ignoredControllerIdentifiers
 *
 * Все компоненты — EAGER (импортируются при старте и регистрируются как классы).
 * Это осознанный выбор: Stimulus 3.2.2 в Application.register НЕ принимает
 * колбэк-функции (() => import(...)) — у неё нет статического shouldLoad,
 * поэтому loadDefinition не вызывается и контроллер молча не регистрируется.
 * Регистрация через класс: application.register(name, CtrlModule.default).
 *
 * ignoredControllerIdentifiers в .stimulus-lsp/config.json синхронизируется
 * с набором всех контроллеров, чтобы stimulus-lsp (строгое равенство в
 * includes, без glob) не выдавал ложные stimulus.controller.invalid для
 * генерируемых панельных/табличных компонентов.
 *
 * Запуск: node scripts/discover_components.js
 * Автоматически вызывается перед esbuild сборкой.
 */

const fs = require('fs')
const path = require('path')

const COMPONENTS_DIR = path.join(process.cwd(), 'app/components')
const OUTPUT_INDEX_JS = path.join(process.cwd(), 'app/javascript/controllers/_components_index.js')
const OUTPUT_CSS = path.join(process.cwd(), 'app/javascript/controllers/_components.css')
const STIMULUS_LSP_CONFIG = path.join(process.cwd(), '.stimulus-lsp/config.json')

function pathToControllerName(filePath) {
  const withoutSuffix = filePath.replace(/_controller\.js$/, '')
  const segments = withoutSuffix.split('/')
  const uniqueSegments = []
  for (let i = 0; i < segments.length; i++) {
    if (i === segments.length - 1 && i > 0 && segments[i] === segments[i - 1]) continue
    uniqueSegments.push(segments[i])
  }
  return uniqueSegments.map(s => s.replace(/_/g, '-')).join('--')
}

function scanFiles(dir, pattern) {
  const results = []
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      const relativePath = path.relative(COMPONENTS_DIR, fullPath)
      if (entry.isDirectory()) {
        results.push(...scanFiles(fullPath, pattern))
      } else if (entry.isFile() && entry.name.endsWith(pattern)) {
        results.push(relativePath)
      }
    }
  } catch (err) {
    console.error(`❌ discover_components: Error scanning ${dir}: ${err.message}`)
  }
  return results
}

function generateIndexJS(controllerFiles) {
  const lines = [
    '// Auto-generated by scripts/discover_components.js',
    '// ALL controllers are EAGER (imported at startup) — registered as classes.',
    '// Stimulus 3.2.2 requires a real class in application.register; a callback',
    '// () => import(...) has no shouldLoad and is silently skipped.',
    '// Do not edit manually',
    '',
    'import { application } from "./application"',
    '',
  ]

  controllerFiles.forEach((file, index) => {
    const controllerName = pathToControllerName(file)
    const rawPath = path.relative(
      path.join(process.cwd(), 'app/javascript/controllers'),
      path.join(COMPONENTS_DIR, file)
    )
    const importPath = rawPath.startsWith('.') ? rawPath : './' + rawPath
    lines.push(`import Ctrl${index} from '${importPath}'`)
    lines.push(`application.register('${controllerName}', Ctrl${index})`)
    lines.push('')
  })

  fs.writeFileSync(OUTPUT_INDEX_JS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_INDEX_JS} (${controllerFiles.length} eager controllers)`)
}

function generateCSS(cssFiles) {
  const lines = [
    '/* Auto-generated by scripts/discover_components.js */',
    '/* Do not edit manually — CSS content is inlined, not @import */',
    '',
  ]

  for (const file of cssFiles) {
    const fullPath = path.join(COMPONENTS_DIR, file)
    try {
      const content = fs.readFileSync(fullPath, 'utf-8').trim()
      if (!content || (content.startsWith('/*') && content.endsWith('*/'))) continue
      lines.push(`/* === ${file} === */`)
      lines.push(content)
      lines.push('')
    } catch (err) {
      console.warn(`⚠️  discover_components: Could not read ${file}: ${err.message}`)
    }
  }

  fs.writeFileSync(OUTPUT_CSS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_CSS} (${cssFiles.length} CSS files)`)
}

/**
 * generateStimulusLspConfig
 *
 * Перезаписывает ignoredControllerIdentifiers в .stimulus-lsp/config.json
 * из набора всех генерируемых lazy-контроллеров.
 *
 * Стимулус-LSP (diagnostics.js:350) использует СТРОГОЕ равенство (includes),
 * без поддержки glob. Поэтому чтобы подавить ложные предупреждения
 * "controller.is.invalid" для генерируемых контроллеров, каждый id
 * должен числиться в конфиге явно.
 *
 * Сохраняет version/createdAt и ignoredAttributes, обновляет updatedAt.
 */
function generateStimulusLspConfig(controllerFiles) {
  const identifiers = controllerFiles.map(pathToControllerName).sort()

  let config
  if (fs.existsSync(STIMULUS_LSP_CONFIG)) {
    try {
      config = JSON.parse(fs.readFileSync(STIMULUS_LSP_CONFIG, 'utf-8'))
    } catch (err) {
      console.warn(`⚠️  discover_components: Could not parse ${STIMULUS_LSP_CONFIG}: ${err.message}; regenerating`)
      config = {}
    }
  } else {
    config = {}
  }

  config.version = '1.1.2'
  config.createdAt = config.createdAt || new Date().toISOString()
  config.updatedAt = new Date().toISOString()
  config.options = config.options || {}
  config.options.ignoredControllerIdentifiers = Array.from(new Set(identifiers)).sort()
  config.options.ignoredAttributes = config.options.ignoredAttributes || []

  fs.mkdirSync(path.dirname(STIMULUS_LSP_CONFIG), { recursive: true })
  fs.writeFileSync(STIMULUS_LSP_CONFIG, JSON.stringify(config, null, 2) + '\n')
  console.log(`✅ discover_components: Updated ${STIMULUS_LSP_CONFIG} (${identifiers.length} ignored controllers)`)
}

function generate() {
  console.log('🔍 discover_components: Scanning app/components/...')

  const controllerFiles = scanFiles(COMPONENTS_DIR, '_controller.js')
  const cssFiles = scanFiles(COMPONENTS_DIR, '.css')

  generateIndexJS(controllerFiles)
  generateCSS(cssFiles)
  generateStimulusLspConfig(controllerFiles)

  controllerFiles.forEach(f => console.log(`   EAGER → ${pathToControllerName(f)}`))
  cssFiles.forEach(f => console.log(`   CSS → ${f}`))
}

generate()
