#!/usr/bin/env node

/**
 * discover_components.js
 *
 * Сканирует app/components/ на наличие Stimulus-контроллеров (*_controller.js)
 * и CSS-файлов (*.css), генерирует:
 *   1. app/javascript/controllers/_components_index.js  — статические импорты (ui/*)
 *   2. app/javascript/controllers/_components_lazy.js   — ленивые импорты (admin/*, poi/*, ...)
 *   3. app/javascript/controllers/_components.css       — импорт всех sidecar CSS
 *
 * Разделение:
 *   - components/ui/*  → статический импорт (всегда в бандле)
 *   - Всё остальное     → ленивый импорт (code-split, chunks/)
 *
 * Запуск: node scripts/discover_components.js
 * Автоматически вызывается перед esbuild сборкой.
 *
 * Соглашение об именовании:
 *   components/foo/bar_component/bar_component_controller.js → foo--bar-component
 */

const fs = require('fs')
const path = require('path')

const COMPONENTS_DIR = path.join(process.cwd(), 'app/components')
const OUTPUT_JS = path.join(process.cwd(), 'app/javascript/controllers/_components_index.js')
const OUTPUT_LAZY_JS = path.join(process.cwd(), 'app/javascript/controllers/_components_lazy.js')
const OUTPUT_CSS = path.join(process.cwd(), 'app/javascript/controllers/_components.css')

/**
 * Конвертирует путь файла относительно components/ в имя Stimulus-контроллера
 */
function pathToControllerName(filePath) {
  const withoutSuffix = filePath.replace(/_controller\.js$/, '')
  const segments = withoutSuffix.split('/')

  const uniqueSegments = []
  for (let i = 0; i < segments.length; i++) {
    if (i === segments.length - 1 && i > 0 && segments[i] === segments[i - 1]) {
      continue
    }
    uniqueSegments.push(segments[i])
  }

  return uniqueSegments.map(s => s.replace(/_/g, '-')).join('--')
}

/**
 * Определяет, является ли компонент "ленивым" (lazy).
 * ui/* — всегда статические (always-on).
 * Всё остальное — ленивое (code-split).
 */
function isLazyComponent(filePath) {
  return !filePath.startsWith('ui/')
}

/**
 * Рекурсивно сканирует директорию на наличие файлов по паттерну
 */
function scanFiles(dir, pattern) {
  const results = []
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      const relativePath = path.relative(COMPONENTS_DIR, fullPath)
      if (entry.isDirectory()) {
        results.push(...scanFiles(fullPath, pattern))
      } else if (entry.isFile() && entry.name.endsWith(pattern)) {
        results.push(relativePath)
      }
    }
  } catch (err) {
    console.error(`❌ discover_components: Error scanning ${dir}: ${err.message}`)
  }
  return results
}

/**
 * Генерирует файл статических импортов (_components_index.js)
 * Только ui/* компоненты — всегда в бандле.
 */
function generateStaticJS(controllerFiles) {
  const staticFiles = controllerFiles.filter(f => !isLazyComponent(f))

  if (staticFiles.length === 0) {
    fs.writeFileSync(OUTPUT_JS, '// No static component controllers found\n')
    console.log(`✅ discover_components: Generated ${OUTPUT_JS} (0 static controllers)`)
    return
  }

  const lines = [
    '// Auto-generated by scripts/discover_components.js',
    '// Static imports — always included in main bundle',
    '// Do not edit manually',
    '',
    'import { application } from "./application"',
    '',
  ]

  for (const file of staticFiles) {
    const controllerName = pathToControllerName(file)
    const rawPath = path.relative(
      path.join(process.cwd(), 'app/javascript/controllers'),
      path.join(COMPONENTS_DIR, file)
    )
    const importPath = rawPath.startsWith('.') ? rawPath : './' + rawPath

    const safeName = controllerName.replace(/[^a-zA-Z0-9_$]/g, '_')
    lines.push(`import ${safeName}Controller from '${importPath}'`)
    lines.push(`application.register('${controllerName}', ${safeName}Controller)`)
    lines.push('')
  }

  fs.writeFileSync(OUTPUT_JS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_JS} (${staticFiles.length} static controllers)`)
}

/**
 * Генерирует файл ленивых импортов (_components_lazy.js)
 * Все не-ui/* компоненты — динамические import().
 * Stimulus примет factory-функцию и вызовет её при появлении data-controller в DOM.
 */
function generateLazyJS(controllerFiles) {
  const lazyFiles = controllerFiles.filter(f => isLazyComponent(f))

  if (lazyFiles.length === 0) {
    fs.writeFileSync(OUTPUT_LAZY_JS, '// No lazy component controllers found\n')
    console.log(`✅ discover_components: Generated ${OUTPUT_LAZY_JS} (0 lazy controllers)`)
    return
  }

  const lines = [
    '// Auto-generated by scripts/discover_components.js',
    '// Lazy (code-split) imports — loaded on-demand via Stimulus lazy API',
    '// Do not edit manually',
    '',
    'import { application } from "./application"',
    '',
  ]

  for (const file of lazyFiles) {
    const controllerName = pathToControllerName(file)
    const rawPath = path.relative(
      path.join(process.cwd(), 'app/javascript/controllers'),
      path.join(COMPONENTS_DIR, file)
    )
    const importPath = rawPath.startsWith('.') ? rawPath : './' + rawPath

    // Stimulus lazy loading: register with a factory function
    // esbuild will create a separate chunk for each dynamic import
    lines.push(
      `application.register('${controllerName}', () => import('${importPath}'))`
    )
    lines.push('')
  }

  fs.writeFileSync(OUTPUT_LAZY_JS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_LAZY_JS} (${lazyFiles.length} lazy controllers)`)
}

function generateCSS(cssFiles) {
  if (cssFiles.length === 0) {
    fs.writeFileSync(OUTPUT_CSS, '/* No component CSS found */\n')
    return
  }

  const lines = [
    '/* Auto-generated by scripts/discover_components.js */',
    '/* Do not edit manually — CSS content is inlined, not @import */',
    '',
  ]

  for (const file of cssFiles) {
    const fullPath = path.join(COMPONENTS_DIR, file)
    try {
      const content = fs.readFileSync(fullPath, 'utf-8').trim()
      if (!content || (content.startsWith('/*') && content.endsWith('*/'))) {
        continue  // Skip empty/stub files
      }
      lines.push(`/* === ${file} === */`)
      lines.push(content)
      lines.push('')
    } catch (err) {
      console.warn(`⚠️  discover_components: Could not read ${file}: ${err.message}`)
    }
  }

  fs.writeFileSync(OUTPUT_CSS, lines.join('\n'))
  console.log(`✅ discover_components: Generated ${OUTPUT_CSS} (${cssFiles.length} CSS files)`)
}

function generate() {
  console.log('🔍 discover_components: Scanning app/components/...')

  const controllerFiles = scanFiles(COMPONENTS_DIR, '_controller.js')
  const cssFiles = scanFiles(COMPONENTS_DIR, '.css')

  generateStaticJS(controllerFiles)
  generateLazyJS(controllerFiles)
  generateCSS(cssFiles)

  controllerFiles.forEach(f => {
    const kind = isLazyComponent(f) ? 'LAZY' : 'STATIC'
    console.log(`   ${kind} → ${pathToControllerName(f)}`)
  })
  cssFiles.forEach(f => console.log(`   CSS → ${f}`))
}

generate()
